/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppPagination: typeof import('./src/components/common/AppPagination.vue')['default']
    CategoryPills: typeof import('./src/components/business/CategoryPills.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    EntryCard: typeof import('./src/components/business/EntryCard.vue')['default']
    HtmlPreview: typeof import('./src/components/business/HtmlPreview.vue')['default']
    ImageUploader: typeof import('./src/components/business/ImageUploader.vue')['default']
    PageSkeleton: typeof import('./src/components/common/PageSkeleton.vue')['default']
    PromptBlock: typeof import('./src/components/business/PromptBlock.vue')['default']
    PromptEditor: typeof import('./src/components/business/PromptEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
